# Generated by Django 6.0 on 2026-02-23 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0008_bookingevent_booking_package_alter_booking_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_review', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_worker_reviews', to=settings.AUTH_USER_MODEL)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.workerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['worker_profile', 'created_at'], name='accounts_wo_worker__eb0c29_idx'), models.Index(fields=['client', 'created_at'], name='accounts_wo_client__c6df58_idx')],
            },
        ),
    ]
