# Generated by Django 6.0 on 2026-02-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
