# Generated by Django 6.0 on 2026-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workerprofile_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='khalti_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
