# Generated by Django 6.0 on 2026-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='pending_admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
