# Generated by Django 6.0 on 2026-02-18 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingnegotiation'),
        ('services', '0002_servicepackage_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingnegotiation',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='initial_price_snapshot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='negotiated_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='bookingnegotiation',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='bookingnegotiation',
            name='is_rejected',
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service'),
        ),
        migrations.AlterField(
            model_name='bookingnegotiation',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
