# Generated by Django 6.0 on 2026-02-19 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingnegotiation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingnegotiation',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='bookingnegotiation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='bookingnegotiation',
            name='sender_role',
        ),
        migrations.AddField(
            model_name='bookingnegotiation',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingnegotiation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('NEGOTIATING', 'Negotiating'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingnegotiation',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
