# Generated by Django 6.0 on 2026-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingnegotiation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price after negotiation', max_digits=10, null=True),
        ),
    ]
