# Generated by Django 6.0 on 2026-02-20 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_final_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingnegotiation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingnegotiation',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_negotiations', to=settings.AUTH_USER_MODEL),
        ),
    ]
