# Generated by Django 6.0 on 2026-02-20 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingnegotiation_message_and_more'),
        ('services', '0002_servicepackage_alter_service_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CANCELED', 'Booking Canceled'), ('BOOKING_CLAIMED', 'Booking Claimed'), ('NEGOTIATION_PROPOSED', 'Negotiation Proposed'), ('NEGOTIATION_ACCEPTED', 'Negotiation Accepted'), ('NEGOTIATION_REJECTED', 'Negotiation Rejected'), ('STATUS_CHANGED', 'Status Changed'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED', 'Job Completed'), ('LOCATION_UPDATE', 'Location Update')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_bookings', to='services.servicepackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service'),
        ),
        migrations.AlterField(
            model_name='bookingnegotiation',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_negotiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingnegotiation',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookingnegotiation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'created_at'], name='bookings_bo_client__0a5142_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['worker', 'created_at'], name='bookings_bo_worker__dea28c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnegotiation',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_980347_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnegotiation',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_7574d3_idx'),
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_d5ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['event_type', 'created_at'], name='bookings_bo_event_t_245e33_idx'),
        ),
    ]
