# Generated by Django 6.0 on 2026-02-18 16:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing_unit',
            field=models.CharField(choices=[('HOUR', 'Per Hour'), ('FIXED', 'Fixed Price')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicepackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='services.service')),
            ],
            options={
                'unique_together': {('package', 'service')},
            },
        ),
    ]
