# Generated by Django 6.0 on 2026-03-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicepackage_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
