# Generated by Django 6.0 on 2026-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='khalti_pidx',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
