# Generated by Django 6.0 on 2026-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_khalti_pidx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
