# Generated by Django 6.0 on 2026-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING_SETTLEMENT', 'Pending Settlement'), ('SETTLED', 'Settled')], default='NOT_APPLICABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='worker_wallet_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('KHALTI', 'Khalti')], max_length=10, null=True),
        ),
    ]
